<a href="https://colab.research.google.com/github/fionasylvester/PDV-assignments/blob/main/Numpy_assignment(pdv).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1.Create a 4X2 integer array and Prints its attributes

In [24]:
import numpy as np
a= np.random.randint(100,size=(4,2))
print(a)

print("the array shape is : ",a.shape)
print("the array dimension is : ",a.ndim)
print("the size of each element in the array is :", a.itemsize)

[[18 12]
 [65 23]
 [ 1 65]
 [67 47]]
the array shape is :  (4, 2)
the array dimension is :  2
the size of each element in the array is : 8


# 2. Create a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10

In [ ]:
a= np.arange(100,200,10).reshape(5,2)
a

array([[100, 110],
       [120, 130],
       [140, 150],
       [160, 170],
       [180, 190]])

# 3. Return array of odd rows and even columns from NumPy array of your choice

In [3]:
a = np.array([[ 1,  2,  3,  4,  5],
[ 6,  7,  8,  9, 10],
[11, 12, 13, 14, 15],
[16, 17, 18, 19, 20]])

a[::2, 1::2]

array([[ 2,  4],
       [12, 14]])

# 4. Create a result array by adding the following two NumPy arrays. Next, modify the result array by calculating the square of each element

In [7]:
a= np.array([[ 1,  2,  3,  4,  5],
[ 6,  7,  8,  9, 10]])
b= np.array([[ 11,  12,  13,  14,  15],
[ 16,  17,  18,  19, 20]])
c= a+b

print(c*c)

[[144 196 256 324 400]
 [484 576 676 784 900]]


# 5.Split the array into four equal-sized sub-arrays

In [11]:
a = np.array([[ 1,  2,  3,  4,  5],
[ 6,  7,  8,  9, 10],
[11, 12, 13, 14, 15],
[16, 17, 18, 19, 20]])

b=np.split(a,4)

print(b)

[array([[1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10]]), array([[11, 12, 13, 14, 15]]), array([[16, 17, 18, 19, 20]])]


# 6.Print max from axis 0 and minfrom axis 1 from the 2-D arrayof your choice.

In [20]:
a = np.array([
[ 100,  2,  3,  4,  5],
[ 6,  7,  8,  908, 10],
[45, 12, 22, 14, 15],
[69, 17, 18, 19, 20]])

min= np.amin(a,1)
max= np.amax(a,0)

print("the max of axis 0 :",max)
print("the min of axis 1:", min)

the max of axis 0 : [100  17  22 908  20]
the min of axis 1: [ 2  6 12 17]


# 7.Delete the second column from a givenarray and insert the new column in its place.

In [39]:
a = np.array([
[ 100,  2,  3,  4,  5],
[ 6,  7,  8,  908, 10],
[45, 12, 22, 14, 15],
[69, 17, 18, 19, 20]])

a= np.delete(a,1,1)

b=([11,11,11,11])

np.insert(a,1,b,1)

array([[100,  11,   3,   4,   5],
       [  6,  11,   8, 908,  10],
       [ 45,  11,  22,  14,  15],
       [ 69,  11,  18,  19,  20]])